=== IIIF/presentation-validator/schema/v4/AnnotationPage.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://iiif.io/api/presentation/4.0/schema/AnnotationPage.json",
    "type": "object",
    "title": "AnnotationPage",
    "description": "id, type and items required",
    "properties": {
        "@context": {
            "$ref": "Context.json"
        },
        "id": {
            "$ref": "properties.json#/$defs/id"
        },
        "type": {
            "type": "string",
            "pattern": "^AnnotationPage$",
            "default": "AnnotationPage"
        },
        "rendering": {
            "$ref": "External.json"
        },
        "label": {
            "$ref": "properties.json#/$defs/lngString"
        },
        "service": {
            "$ref": "Service.json"
        },
        "thumbnail": {
            "type": "array",
            "items": {
                "$ref": "Resource.json"
            }
        },
        "items": {
            "type": "array",
            "items": {
                "$ref": "Annotation.json"
            }
        },
        "partOf": {
            "$ref": "PartOf.json"
        },
        "next": {
            "$ref": "AnnotationPageRef.json"
        },
        "prev": {
            "$ref": "AnnotationPageRef.json"
        },
        "first": {
            "$ref": "AnnotationPageRef.json"
        },
        "last": {
            "$ref": "AnnotationPageRef.json"
        }
    },
    "required": [
        "id",
        "type",
        "items"
    ]
}

=== IIIF/presentation-validator/fixtures/3/valid/0306-manifest-link-annos.json
{
  "@context": "http://iiif.io/api/presentation/3/context.json",
  "id": "https://preview.iiif.io/cookbook/0306-linking-annotations-to-manifests/recipe/0306-linking-annotations-to-manifests/annotationpage.json",
  "type": "AnnotationPage",
  "items": [
    {
      "id": "https://preview.iiif.io/cookbook/0306-linking-annotations-to-manifests/recipe/0306-linking-annotations-to-manifests/canvas-1/annopage-2/anno-1",
      "type": "Annotation",
      "motivation": "commenting",
      "body": {
        "type": "TextualBody",
        "language": "de",
        "format": "text/plain",
        "value": "Der GÃ¤nseliesel-Brunnen"
      },
      "target": {
        "type": "SpecificResource",
        "source": {
          "id": "https://preview.iiif.io/cookbook/0306-linking-annotations-to-manifests/recipe/0306-linking-annotations-to-manifests/canvas-1",
          "type": "Canvas",
          "partOf": [
            {
              "id": "https://preview.iiif.io/cookbook/0306-linking-annotations-to-manifests/recipe/0306-linking-annotations-to-manifests/annotationpage.json",
              "type": "Manifest"
            }
          ]
        },
        "selector": {
          "type": "FragmentSelector",
          "conformsTo": "http://www.w3.org/TR/media-frags/",
          "value": "xywh=300,800,1200,1200"
        }
      }
    }
  ]
}

=== IIIF/presentation-validator/fixtures/4/ok/02_timeline.json
{
  "@context": "http://iiif.io/api/presentation/4/context.json",
  "id": "https://iiif.io/api/presentation/4.0/example/02_timeline.json",
  "type": "Manifest",
  "label": {
    "en": [
      "Simplest Audio Example (IIIF Presentation v4)"
    ]
  },
  "items": [
    {
      "id": "https://iiif.io/api/presentation/4.0/example/02",
      "type": "Timeline",
      "duration": 1985.024,
      "items": [
        {
          "id": "https://iiif.io/api/presentation/4.0/example/02/page",
          "type": "AnnotationPage",
          "items": [
            {
              "id": "https://iiif.io/api/presentation/4.0/example/02/page/anno",
              "type": "Annotation",
              "motivation": ["painting"],
              "body": {
                "id": "https://fixtures.iiif.io/audio/indiana/mahler-symphony-3/CD1/medium/128Kbps.mp4",
                "type": "Audio",
                "format": "audio/mp4",
                "duration": 1985.024
              },
              "target": {
                "id": "https://iiif.io/api/presentation/4.0/example/02",
                "type": "Timeline"
              }
            }
          ]
        }
      ]
    }
  ]
}

=== IIIF/presentation-validator/fixtures/3/anno_source.json
{
  "@context": "http://iiif.io/api/presentation/3/context.json",
  "id": "https://preview.iiif.io/cookbook/0326-annotating-image-layer/recipe/0326-annotating-image-layer/manifest.json",
  "type": "Manifest",
  "label": {
    "en": [
      "Choice Example with layer specific annotation"
    ]
  },
  "items": [
    {
      "id": "https://preview.iiif.io/cookbook/0326-annotating-image-layer/recipe/0326-annotating-image-layer/canvas/p1",
      "type": "Canvas",
      "height": 1271,
      "width": 2000,
      "items": [
        {
          "id": "https://preview.iiif.io/cookbook/0326-annotating-image-layer/recipe/0326-annotating-image-layer/page/p1/1",
          "type": "AnnotationPage",
          "items": [
            {
              "id": "https://preview.iiif.io/cookbook/0326-annotating-image-layer/recipe/0326-annotating-image-layer/annotation/p0001-image",
              "type": "Annotation",
              "motivation": "painting",
              "body": {
                "type": "Choice",
                "items": [
                  {
                    "id": "https://iiif.io/api/image/3.0/example/reference/421e65be2ce95439b3ad6ef1f2ab87a9-dee-natural/full/max/0/default.jpg",
                    "type": "Image",
                    "label": {
                      "en": [
                        "Natural Light"
                      ]
                    },
                    "format": "image/jpeg",
                    "height": 1271,
                    "width": 2000,
                    "service": [
                      {
                        "id": "https://iiif.io/api/image/3.0/example/reference/421e65be2ce95439b3ad6ef1f2ab87a9-dee-natural",
                        "type": "ImageService3",
                        "profile": "level1"
                      }
                    ]
                  },
                  {
                    "id": "https://iiif.io/api/image/3.0/example/reference/421e65be2ce95439b3ad6ef1f2ab87a9-dee-xray/full/max/0/default.jpg",
                    "type": "Image",
                    "label": {
                      "en": [
                        "X-Ray"
                      ]
                    },
                    "format": "image/jpeg",
                    "height": 1271,
                    "width": 2000,
                    "service": [
                      {
                        "id": "https://iiif.io/api/image/3.0/example/reference/421e65be2ce95439b3ad6ef1f2ab87a9-dee-xray",
                        "type": "ImageService3",
                        "profile": "level1"
                      }
                    ],
                    "annotations": [
                      {
                        "id": "https://preview.iiif.io/cookbook/0326-annotating-image-layer/recipe/0326-annotating-image-layer/page/p2/1",
                        "type": "AnnotationPage",
                        "items": [
                          {
                            "id": "https://preview.iiif.io/cookbook/0326-annotating-image-layer/recipe/0326-annotating-image-layer/annotation/p0002-tag",
                            "type": "Annotation",
                            "motivation": "tagging",
                            "body": {
                              "type": "TextualBody",
                              "value": "A group of skulls.",
                              "language": "en",
                              "format": "text/plain"
                            },
                            "target": {
                              "source": "https://iiif.io/api/image/3.0/example/reference/421e65be2ce95439b3ad6ef1f2ab87a9-dee-xray/full/max/0/default.jpg#xywh=810,900,260,370",
                              "scope": "https://preview.iiif.io/cookbook/0326-annotating-image-layer/recipe/0326-annotating-image-layer/canvas/p1"
                            }
                          }
                        ]
                      }
                    ]
                  }
                ]
              },
              "target": "https://preview.iiif.io/cookbook/0326-annotating-image-layer/recipe/0326-annotating-image-layer/canvas/p1"
            }
          ]
        }
      ]
    }
  ]
}
