=== IIIF/presentation-validator/schema/v4/AnnotationPage.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://iiif.io/api/presentation/4.0/schema/AnnotationPage.json",
    "type": "object",
    "title": "AnnotationPage",
    "description": "id, type and items required",
    "properties": {
        "@context": {
            "$ref": "Context.json"
        },
        "id": {
            "$ref": "properties.json#/$defs/id"
        },
        "type": {
            "type": "string",
            "pattern": "^AnnotationPage$",
            "default": "AnnotationPage"
        },
        "rendering": {
            "$ref": "External.json"
        },
        "label": {
            "$ref": "properties.json#/$defs/lngString"
        },
        "service": {
            "$ref": "Service.json"
        },
        "thumbnail": {
            "type": "array",
            "items": {
                "$ref": "Resource.json"
            }
        },
        "items": {
            "type": "array",
            "items": {
                "$ref": "Annotation.json"
            }
        },
        "partOf": {
            "$ref": "PartOf.json"
        },
        "next": {
            "$ref": "AnnotationPageRef.json"
        },
        "prev": {
            "$ref": "AnnotationPageRef.json"
        },
        "first": {
            "$ref": "AnnotationPageRef.json"
        },
        "last": {
            "$ref": "AnnotationPageRef.json"
        }
    },
    "required": [
        "id",
        "type",
        "items"
    ]
}

=== IIIF/presentation-validator/fixtures/3/valid/annoPage.json
{
  "@context": "http://iiif.io/api/presentation/3/context.json",
  "id": "https://preview.iiif.io/cookbook/0068-newspaper/recipe/0068-newspaper/newspaper_issue_1-anno_p1.json",
  "type": "AnnotationPage",
  "items": [
    {
      "id": "https://data.europeana.eu/annotation/9200355/BibliographicResource_3000096302513/20b3b1f4cb15f062e53fd50d584d66ff",
      "type": "Annotation",
      "motivation": "supplementing",
      "body": {
        "type": "TextualBody",
        "format": "text/plain",
        "language": "de",
        "value": "84"
      },
      "target": "https://iiif.europeana.eu/presentation/9200355/BibliographicResource_3000096302513/canvas/p1#xywh=182,476,59,43"
    }
  ]
}

=== IIIF/presentation-validator/fixtures/3/annotation_full.json
{
    "@context": "http://iiif.io/api/presentation/3/context.json",
    "id": "https://example.org/iiif/book1/annopage/p1",
    "type": "AnnotationPage",
    "items": [
        {
            "id": "http://example.org/anno38",
            "type": "Annotation",
            "motivation": "commenting",
            "creator": {
                "id": "http://example.org/user1",
                "type": "Person",
                "name": "A. Person",
                "nickname": "user1"
            },
            "created": "2015-10-13T13:00:00Z",
            "generator": {
                "id": "http://example.org/client1",
                "type": "Software",
                "name": "Code v2.1",
                "homepage": "http://example.org/homepage1"
            },
            "generated": "2015-10-14T15:13:28Z",
            "stylesheet": {
                "id": "http://example.org/stylesheet1",
                "type": "CssStylesheet"
            },
            "body": [
                {
                    "type": "TextualBody",
                    "purpose": "tagging",
                    "value": "love"
                },
                {
                    "type": "Choice",
                    "items": [
                        {
                            "type": "TextualBody",
                            "purpose": "describing",
                            "value": "I really love this particular bit of text in this XML. No really.",
                            "format": "text/plain",
                            "language": "en",
                            "creator": "http://example.org/user1"
                        },
                        {
                            "type": "SpecificResource",
                            "purpose": "describing",
                            "source": {
                                "id": "http://example.org/comment1",
                                "type": "Audio",
                                "format": "audio/mpeg",
                                "language": "de",
                                "creator": {
                                    "id": "http://example.org/user2",
                                    "type": "Person"
                                }
                            }
                        }
                    ]
                }
            ],
            "target": {
                "type": "SpecificResource",
                "styleClass": "mystyle",
                "source": "http://example.com/document1",
                "state": [
                    {
                        "type": "HttpRequestState",
                        "value": "Accept: application/xml",
                        "refinedBy": {
                            "type": "TimeState",
                            "sourceDate": "2015-09-25T12:00:00Z"
                        }
                    }
                ],
                "selector": {
                    "type": "FragmentSelector",
                    "value": "xpointer(/doc/body/section[2]/para[1])",
                    "refinedBy": {
                        "type": "TextPositionSelector",
                        "start": 6,
                        "end": 27
                    }
                }
            }
        }
    ]
}

=== IIIF/presentation-validator/fixtures/3/annoPageInCollection.json
{
    "@context": "http://iiif.io/api/presentation/3/context.json",
    "id": "https://preview.iiif.io/cookbook/309-annotation-collections/recipe/0309-annotation-collection/anno_p1.json",
    "type": "AnnotationPage",
    "partOf": [{
        "id": "https://preview.iiif.io/cookbook/309-annotation-collections/recipe/0309-annotation-collection/anno_coll.json",
        "type": "AnnotationCollection"
    }],
    "next": {
        "id": "https://preview.iiif.io/cookbook/309-annotation-collections/recipe/0309-annotation-collection/anno_p2.json",
        "type": "AnnotationPage"
    },
    "items": [
        {
            "id": "https://preview.iiif.io/cookbook/309-annotation-collections/recipe/0309-annotation-collection/anno_p1.json-1",
            "type": "Annotation",
            "motivation": "tagging",
            "body": {
                "type": "TextualBody",
                "format": "text/plain",
                "value": "text-1-1"
            },
            "target": {
                "type": "SpecificResource",
                "source": {
                    "id": "https://preview.iiif.io/cookbook/309-annotation-collections/recipe/0309-annotation-collection/canvas/p1",
                    "type": "Canvas",
                    "partOf": [{
                        "id": "https://preview.iiif.io/cookbook/309-annotation-collections/recipe/0309-annotation-collection/manifest.json",
                        "type": "Manifest"
                    }]
                },
                "selector": {
                    "type": "FragmentSelector",
                    "conformsTo": "http://www.w3.org/TR/media-frags/",
                    "value": "xywh=88,957,2768,248"
                }
            }
        }
    ]
}

=== IIIF/presentation-validator/fixtures/3/valid/0306-manifest-link-manifest.json
{
  "@context": "http://iiif.io/api/presentation/3/context.json",
  "id": "https://preview.iiif.io/cookbook/0306-linking-annotations-to-manifests/recipe/0306-linking-annotations-to-manifests/manifest.json",
  "type": "Manifest",
  "label": {
    "en": [
      "Picture of GÃ¶ttingen taken during the 2019 IIIF Conference"
    ]
  },
  "items": [
    {
      "id": "https://preview.iiif.io/cookbook/0306-linking-annotations-to-manifests/recipe/0306-linking-annotations-to-manifests/canvas-1",
      "type": "Canvas",
      "height": 3024,
      "width": 4032,
      "items": [
        {
          "id": "https://preview.iiif.io/cookbook/0306-linking-annotations-to-manifests/recipe/0306-linking-annotations-to-manifests/canvas-1/annopage-1",
          "type": "AnnotationPage",
          "items": [
            {
              "id": "https://preview.iiif.io/cookbook/0306-linking-annotations-to-manifests/recipe/0306-linking-annotations-to-manifests/canvas-1/annopage-1/anno-1",
              "type": "Annotation",
              "motivation": "painting",
              "body": {
                "id": "https://iiif.io/api/image/3.0/example/reference/918ecd18c2592080851777620de9bcb5-gottingen/full/max/0/default.jpg",
                "type": "Image",
                "format": "image/jpeg",
                "height": 3024,
                "width": 4032,
                "service": [
                  {
                    "id": "https://iiif.io/api/image/3.0/example/reference/918ecd18c2592080851777620de9bcb5-gottingen",
                    "profile": "level1",
                    "type": "ImageService3"
                  }
                ]
              },
              "target": "https://preview.iiif.io/cookbook/0306-linking-annotations-to-manifests/recipe/0306-linking-annotations-to-manifests/canvas-1"
            }
          ]
        }
      ],
      "annotations": [
        {
          "id": "https://preview.iiif.io/cookbook/0306-linking-annotations-to-manifests/recipe/0306-linking-annotations-to-manifests/annotationpage.json",
          "type": "AnnotationPage"
        }
      ]
    }
  ]
}

=== IIIF/presentation-validator/fixtures/3/anno_pointselector.json
{
  "@context": "http://iiif.io/api/presentation/3/context.json",
  "id": "https://preview.iiif.io/cookbook/0103-poetry/recipe/0103-poetry-reading-annotations/annotations.json",
  "type": "AnnotationPage",
  "items": [
    {
      "id": "https://preview.iiif.io/cookbook/0103-poetry/recipe/0103-poetry-reading-annotations/canvas/annotation1",
      "type": "Annotation",
      "motivation": "commenting",
      "body": {
        "type": "TextualBody",
        "value": "breath",
        "format": "text/plain"
      },
      "target": {
        "type": "SpecificResource",
        "source": "https://preview.iiif.io/cookbook/0103-poetry/recipe/0103-poetry-reading-annotations/canvas/1",
        "selector": {
          "type": "PointSelector",
          "t": 27.660653
        }
      }
    }
  ]
}

=== IIIF/presentation-validator/fixtures/3/multi_bodies.json
{
  "@context": "http://iiif.io/api/presentation/3/context.json",
  "id": "http://localhost:4000/recipe/0219-using-caption-file/manifest.json",
  "type": "Manifest",
  "label": {
    "en": [
      "Lunchroom Manners"
    ]
  },
  "items": [
    {
      "id": "http://localhost:4000/recipe/0219-using-caption-file/canvas",
      "type": "Canvas",
      "height": 360,
      "width": 480,
      "duration": 572.034,
      "items": [
        {
          "id": "http://localhost:4000/recipe/0219-using-caption-file/canvas/page",
          "type": "AnnotationPage",
          "items": [
            {
              "id": "http://localhost:4000/recipe/0219-using-caption-file/canvas/page/annotation",
              "type": "Annotation",
              "motivation": "painting",
              "body": [
                {
                  "id": "https://fixtures.iiif.io/video/indiana/lunchroom_manners/high/lunchroom_manners_1024kb.mp4",
                  "type": "Video",
                  "height": 360,
                  "width": 480,
                  "duration": 572.034,
                  "format": "video/mp4"
                },
                {
                  "id": "https://fixtures.iiif.io/video/indiana/lunchroom_manners/lunchroom_manners.vtt",
                  "type": "Text",
                  "format": "text/vtt",
                  "language": "en"
                }
              ],
              "target": "http://localhost:4000/recipe/0219-using-caption-file/canvas"
            }
          ]
        }
      ]
    }
  ]
}

=== IIIF/presentation-validator/fixtures/3/placeholderCanvas.json
{
  "@context": "http://iiif.io/api/presentation/3/context.json",
  "id": "https://iiif.io/api/cookbook/recipe/0013-placeholderCanvas/manifest.json",
  "type": "Manifest",
  "label": {
    "en": [
      "Video recording of Donizetti's _The Elixer of Love_"
    ]
  },
  "items": [
    {
      "id": "https://iiif.io/api/cookbook/recipe/0013-placeholderCanvas/canvas/donizetti",
      "type": "Canvas",
      "duration": 7278.466,
      "width": 640,
      "height": 360,
      "placeholderCanvas": {
        "id": "https://iiif.io/api/cookbook/recipe/0013-placeholderCanvas/canvas/donizetti/placeholder",
        "type": "Canvas",
        "width": 640,
        "height": 360,
        "items": [
          {
            "id": "https://iiif.io/api/cookbook/recipe/0013-placeholderCanvas/canvas/donizetti/placeholder/1",
            "type": "AnnotationPage",
            "items": [
              {
                "id": "https://iiif.io/api/cookbook/recipe/0013-placeholderCanvas/canvas/donizetti/placeholder/1-image",
                "type": "Annotation",
                "motivation": "painting",
                "body": {
                  "id": "https://fixtures.iiif.io/video/indiana/donizetti-elixir/act1-thumbnail.png",
                  "type": "Image",
                  "format": "image/png",
                  "width": 640,
                  "height": 360
                },
                "target": "https://iiif.io/api/cookbook/recipe/0013-placeholderCanvas/canvas/donizetti/placeholder"
              }
            ]
          }
        ]
      },
      "items": [
        {
          "id": "https://iiif.io/api/cookbook/recipe/0013-placeholderCanvas/donizetti/1",
          "type": "AnnotationPage",
          "items": [
            {
              "id": "https://iiif.io/api/cookbook/recipe/0013-placeholderCanvas/donizetti/1-video",
              "type": "Annotation",
              "motivation": "painting",
              "body": {
                "id": "https://fixtures.iiif.io/video/indiana/donizetti-elixir/vae0637_accessH264_low.mp4",
                "type": "Video",
                "duration": 7278.466,
                "width": 640,
                "height": 360,
                "format": "video/mp4"
              },
              "target": "https://iiif.io/api/cookbook/recipe/0013-placeholderCanvas/canvas/donizetti"
            }
          ]
        }
      ]
    }
  ]
}

=== IIIF/presentation-validator/fixtures/3/valid/version2image.json
{
  "@context": "http://iiif.io/api/presentation/3/context.json",
  "id": "https://example.org/iiif/book1/manifest",
  "type": "Manifest",
  "label": { "en": [ "Book 1" ] },
    "items": [
        {
          "id": "https://example.org/iiif/book1/canvas/p1",
          "type": "Canvas",
          "label": { "none": [ "p. 1" ] },
          "height": 1000,
          "width": 750,
          "items": [
            {
              "id": "https://example.org/iiif/book1/page/p1/1",
              "type": "AnnotationPage",
              "items": [
                {
                  "id": "https://example.org/iiif/book1/annotation/p0001-image",
                  "type": "Annotation",
                  "motivation": "painting",
                  "body": {
                    "id": "https://example.org/iiif/book1/page1/full/full/0/default.jpg",
                    "type": "Image",
                    "format": "image/jpeg",
                    "service": [
                      {
                          "@id": "https://example.org/iiif2/image1/identifier",
                          "@type": "ImageService2",
                          "profile": "http://iiif.io/api/image/2/level2.json"
                      }
                    ],
                    "height": 2000,
                    "width": 1500
                  },
                  "target": "https://example.org/iiif/book1/canvas/p1"
                }
              ]
            }
          ],
          "annotations": [
            {
              "id": "https://example.org/iiif/book1/comments/p1/1",
              "type": "AnnotationPage"
            }
          ]
        }
    ]
}
